version: "3.8"
services:
  postgres:
    image: "11notes/postgres:16"
    container_name: "postgres"
    environment:
      TZ: Europe/Zurich
      POSTGRES_PASSWORD: "whodb"
    volumes:
      - "postgres-var:/postgres/var"
      - "postgres-backup:/postgres/backup"
    networks:
      - postgres
    restart: always
  redis:
    image: "11notes/redis:7.2.5"
    container_name: "redis"
    environment:
      TZ: Europe/Zurich
      REDIS_PASSWORD: "whodb"
    volumes:
      - "redis-etc:/redis/etc"
      - "redis-var:/redis/var"
    networks:
      - redis
    restart: always
  whodb:
    image: "11notes/whodb:latest"
    container_name: "whodb"
    environment:
      TZ: Europe/Zurich
    ports:
      - "8080:8080/tcp"
    networks:
      - postgres
      - redis
      - frontend
    restart: always
volumes:
  postgres-var:
  postgres-backup:
  redis-etc:
  redis-var:
networks:
  postgres:
    internal: true
  redis:
    internal: true
  frontend: