version: "3.8"
services:
  postgres:
    image: "11notes/postgres:16"
    container_name: "postgres"
    environment:
      TZ: Europe/Zurich
      POSTGRES_PASSWORD: *********
    volumes:
      - "postgres-var:/postgres/var"
      - "postgres-backup:/postgres/backup"
    networks:
      - postgres
    restart: always
  whodb:
    image: "11notes/whodb:latest"
    container_name: "whodb"
    environment:
      TZ: Europe/Zurich
    ports:
      - "8080:8080/tcp"
    networks:
      - postgres
      - frontend
    restart: always
volumes:
  postgres-var:
  postgres-backup:
networks:
  postgres:
    internal: true
  frontend: